// // leave off @2x/@3x
// const images = {
//   logoWithBrim: require('../Images/pedal-logo-white-brim.png'),
//   logo: require('../Images/pedal-logo.png'),
//   photoScrollGrid: require('../Images/photo-scroll-grid-ex.png'),
//   fireview: require('../Images/Icons/fireview-icon.png'),
//   pressed: {
//     fireview: require('../Images/Icons/fireview-icon-pressed.png'),
//     brandButton: require('../Images/brand-button-pressed.png'),
//     priceButton: require('../Images/price-button-pressed.png')
//   },
//   clearLogo: require('../Images/top_logo.png'),
//   launch: require('../Images/launch-icon.png'),
//   ready: require('../Images/your-app.png'),
//   ignite: require('../Images/ignite_logo.png'),
//   igniteClear: require('../Images/ignite-logo-transparent.png'),
//   tileBg: require('../Images/tile_bg.png'),
//   background: require('../Images/BG.png'),
//   customerBackground: require('../Images/BG.png'),
//   customerCreateBackground: require('../Images/bgCustomerCreate.png'),
//   dealerBackground: require('../Images/bgDealer.png'),
//   dealerCreateBackground: require('../Images/bgDealerCreate.png'),
//   buttonBackground: require('../Images/button-bg.png'),
//   resetPasswordBackground: require('../Images/bgReset.png'),
//   resetSentBackground: require('../Images/bgResetSent.png'),
//   api: require('../Images/Icons/icon-api-testing.png'),
//   components: require('../Images/Icons/icon-components.png'),
//   deviceInfo: require('../Images/Icons/icon-device-information.png'),
//   faq: require('../Images/Icons/faq-icon.png'),
//   home: require('../Images/Icons/icon-home.png'),
//   theme: require('../Images/Icons/icon-theme.png'),
//   usageExamples: require('../Images/Icons/icon-usage-examples.png'),
//   chevronRight: require('../Images/Icons/chevron-right.png'),
//   hamburger: require('../Images/Icons/hamburger.png'),
//   backButton: require('../Images/Icons/back-button.png'),
//   closeButton: require('../Images/Icons/close-button.png'),
//   userLoginIcon: require('../Images/Icons/user-login-icon.png'),
//   passwordLoginIcon: require('../Images/Icons/password-login-icon.png'),
//   createAddressIcon: require('../Images/Icons/address.png'),
//   createBrandIcon: require('../Images/Icons/brand.png'),
//   createLicenseIcon: require('../Images/Icons/license.png'),
//   createManagerIcon: require('../Images/Icons/manager.png'),
//   createNameIcon: require('../Images/Icons/name.png'),
//   createPhoneIcon: require('../Images/Icons/phone.png'),
//   createPointIcon: require('../Images/Icons/point.png'),
//   createWebsiteIcon: require('../Images/Icons/website.png'),
//   createDealershipIcon: require('../Images/Icons/dealership.png'),
//   tabAccount: require('../Images/Icons/tabs/account.png'),
//   tabAccountActive: require('../Images/Icons/tabs/accountActive.png'),
//   tabShop: require('../Images/Icons/tabs/shop.png'),
//   tabShopActive: require('../Images/Icons/tabs/shopActive.png'),
//   tabFireview: require('../Images/Icons/tabs/fireview.png'),
//   tabFireviewActive: require('../Images/Icons/tabs/fireviewActive.png'),
//   tabSuggestions: require('../Images/Icons/tabs/suggestions.png'),
//   tabSuggestionsActive: require('../Images/Icons/tabs/suggestionsActive.png'),
//   tabPlanner: require('../Images/Icons/tabs/planner.png'),
//   tabPlannerActive: require('../Images/Icons/tabs/plannerActive.png'),
//   shopBackground: require('../Images/shop-wallpaper-bg.png'),
//   brandButton: require('../Images/brand-button.png'),
//   priceButton: require('../Images/price-button.png'),
//   likeIcon: require('../Images/Icons/like.png'),
//   likeActiveIcon: require('../Images/Icons/likeActive.png')
// }

// export default images

// leave off @2x/@3x
const images = {
  logoWithBrim: require('../Images/pedal-logo-white-brim.png'),
  logo: require('../Images/pedal-logo.png'),
  photoScrollGrid: require('../Images/photo-scroll-grid-ex.png'),
  fireview: require('../Images/Icons/fireview-icon.png'),
  pressed: {
    fireview: require('../Images/Icons/fireview-icon-pressed.png'),
    brandButton: require('../Images/brand-button-pressed.png'),
    priceButton: require('../Images/price-button-pressed.png')
  },
  man: require('../Images/man.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  customerBackground: require('../Images/BG.png'),
  customerCreateBackground: require('../Images/bgCustomerCreate.png'),
  dealerBackground: require('../Images/bgDealer.png'),
  dealerCreateBackground: require('../Images/bgDealerCreate.png'),
  buttonBackground: require('../Images/button-bg.png'),
  resetPasswordBackground: require('../Images/bgReset.png'),
  resetSentBackground: require('../Images/bgResetSent.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  userLoginIcon: require('../Images/Icons/user-login-icon.png'),
  passwordLoginIcon: require('../Images/Icons/password-login-icon.png'),
  createAddressIcon: require('../Images/Icons/address.png'),
  createBrandIcon: require('../Images/Icons/brand.png'),
  createLicenseIcon: require('../Images/Icons/license.png'),
  createManagerIcon: require('../Images/Icons/manager.png'),
  createNameIcon: require('../Images/Icons/name.png'),
  createPhoneIcon: require('../Images/Icons/phone.png'),
  createPointIcon: require('../Images/Icons/point.png'),
  createWebsiteIcon: require('../Images/Icons/website.png'),
  createDealershipIcon: require('../Images/Icons/dealership.png'),
  tabAccount: require('../Images/Icons/tabs/account.png'),
  tabAccountActive: require('../Images/Icons/tabs/accountActive.png'),
  tabShop: require('../Images/Icons/tabs/shop.png'),
  tabShopActive: require('../Images/Icons/tabs/shopActive.png'),
  tabFireview: require('../Images/Icons/tabs/fireview.png'),
  tabFireviewActive: require('../Images/Icons/tabs/fireviewActive.png'),
  tabSuggestions: require('../Images/Icons/tabs/suggestions.png'),
  tabSuggestionsActive: require('../Images/Icons/tabs/suggestionsActive.png'),
  tabPlanner: require('../Images/Icons/tabs/planner.png'),
  tabPlannerActive: require('../Images/Icons/tabs/plannerActive.png'),
  shopBackground: require('../Images/shop-wallpaper-bg.png'),
  brandButton: require('../Images/brand-button.png'),
  priceButton: require('../Images/price-button.png'),
  accountBg: require('../Images/Account Page_background_blank.png'),
  accountGearUnclicked: require('../Images/Account- Settings gear unclicked.png'),
  accountGearClicked: require('../Images/Account- Settings gear clicked.png'),
  accountCameraUnclicked: require('../Images/Account- Camera Unclicked.png'),
  accountCameraClicked: require('../Images/Account- Camera Clicked.png'),
  accountDlClicked: require('../Images/Account- DL- Uploaded- saved-Blue.png'),
  accountInfoClicked: require('../Images/Account- Info- uploaded- saved- blue.png'),
  accountInsuranceClicked: require('../Images/Account- Insurance- Uploaded- saved- blue.png'),
  accountDlUnclicked: require('../Images/Account--DL--Uploaded--saved-Gray.png'),
  accountInfoUnclicked: require('../Images/Account--Info--uploaded--saved--gray.png'),
  accountInsuranceUnclicked: require('../Images/Account--Insurance--Uploaded--saved--gray.png'),
  accountDiamondFinished: require('../Images/Account- Diamond Lane- Finished.png'),
  accountDiamondNotFinished: require('../Images/Account- Diamond Lane- Not finished- grayed out.png'),
  accountPedalClicked: require('../Images/Account- Pedal Navigation clicked.png'),
  accountPedalUnclicked: require('../Images/Account- Pedal Navigation Unclicked.png'),
  accountCameraRing: require('../Images/Account--Camera-Ring.png')
}

export default images
